FROM debian:stretch

RUN apt-get update -yqq \
  && apt-get install -yqq --no-install-recommends \
    software-properties-common \
    build-essential \
    libffi-dev \
    libssl-dev \
    python-dev \
    python-pip \
    git \
    systemd \
  && pip install --upgrade setuptools \
  && pip install ansible \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /etc/ansible && echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/bin/systemd"]
