FROM ubuntu:trusty

RUN apt-get update -qq \
 && apt-get dist-upgrade -yqq \
 && apt-get install -yqq software-properties-common \
 && apt-add-repository -y ppa:ansible/ansible \
 && apt-get update -qq \
 && apt-get install -yqq \
    git \
    ansible \
 && rm -rf /var/lib/apt/lists/*

RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts

ENTRYPOINT ["/sbin/init"]
